version: '3.8'
services:
  api:
    build:
      context: ./gateway_api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    entrypoint: bash -c "python unicorn.py"
    volumes:
      - "./gateway_api/src/:/src"
    environment:
      - GOOGLE_MAPS_API_KEY=
      - API_BASE_URL_TERMINAL=
      - API_CLIENT_ID_TERMINAL=
      - API_CLIENT_SECRET_TERMINAL=
      - API_BASE_URL_CARRIER=
      - API_CLIENT_ID_CARRIER=
      - API_CLIENT_SECRET_CARRIER=
      - TOKEN_URL=
    restart: always
    depends_on:
      - redis

  ship:
    build:
      context: ./ship_app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api


  lock:
    build:
      context: ./lock_app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
      - redis
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG,HSCAN