version: '3.8'
services:
  api:
    build:
      context: ./gateway_api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    entrypoint: bash -c "python unicorn.py"
    volumes:
      - "./gateway_api/src/:/src"
    environment:
      - API_BASE_URL_TERMINAL=https://t5terminal.dev-hackathon-202205.dcsa.org/jit/v1/events
      - API_CLIENT_ID_TERMINAL=m9tl6vjsnhg5q9na0oaakqvbp
      - API_CLIENT_SECRET_TERMINAL=8s7gqt4d3n8pu4j63jd1fh8icm0fl8of41uqbsai5obuiog3uk5

      - API_BASE_URL_CARRIER=https://t5carrier.dev-hackathon-202205.dcsa.org/jit/v1/events
      - API_CLIENT_ID_CARRIER=4lk2eooigqbva1lpvo1kb4hieq
      - API_CLIENT_SECRET_CARRIER=1mdutnhu42k873mj59u13krn0dtaabvvksctj3j2rt4psp1lbt46

      - TOKEN_URL=https://9g2pkr41d6.auth.eu-west-1.amazoncognito.com/oauth2/token
    restart: always

  # ship:
  #   build:
  #     context: ./ship_app
  #     dockerfile: Dockerfile   


  lock:
    build:
      context: ./lock_app
      dockerfile: Dockerfile
    restart: always

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG,HSCAN